version: '3'

services:

  web1:
    image: nginx:alpine
    ports:
      - "8091:80"
    volumes:
      - ./web1html:/usr/share/nginx/html

  web2:
    image: nginx:alpine
    ports:
      - "8092:80"
    volumes:
      - ./web2html:/usr/share/nginx/html

  haproxy:
    build: ./haproxy/
    ports:
      - "8090:80"
    volumes:
      - ./haproxy/conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - web1
      - web2