version: '3'

services:

  web1:
    image: nginx:alpine
    volumes:
      - ./web1html:/usr/share/nginx/html

  web2:
    image: nginx:alpine
    volumes:
      - ./web2html:/usr/share/nginx/html

  haproxy:
    build: ./haproxy/
    volumes:
      - ./haproxy/conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - web1
      - web2

  varnish:
    build: ./varnish/
    volumes:
      - ./varnish/conf/default.vcl:/etc/varnish/default.vcl
    depends_on:
      - haproxy
    ports:
      - "80:80"